Create Table SellList(
Pid int Identity(1,1) Not Null,
pNam Nvarchar(50) Not Null,
pCity Nvarchar(50) Not Null,
pArea Nvarchar(50) Not Null,
pAddress Nvarchar(50) Not Null,
plit Nvarchar(50) Not Null,
plng Nvarchar(50) Not Null,
p交易日期 Nvarchar(50) Not Null,
p型態 Nvarchar(50) Not Null,
p成交價 Nvarchar(50) Not Null,
p建坪 Nvarchar(50) Not Null,
p單價 Nvarchar(50) Not Null,
p地坪 Nvarchar(50) Not Null,
p樓別 Nvarchar(50) Not Null,
p屋齡 Nvarchar(50) Not Null,
p車位 Nvarchar(50) Not Null,
CreateTime Nvarchar(50) Not Null
)